platform :ios, "8.0"
inhibit_all_warnings!

target 'Muse' do

pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 1.0.0'

#scrollview上加载textfield/textview,自动滚动内容
pod 'TPKeyboardAvoiding', '~> 1.3'

#网络请求库
pod 'YTKNetwork', '~> 0.6.0'

#密码保存
pod 'SSKeychain', '~> 1.4.0'

#BLE
pod 'BabyBluetooth','~> 0.7.0'

pod 'iCarousel','~> 1.8.2'

#数据库
pod 'FMDB', '~> 2.6.2'

#weibo
pod 'WeiboSDK', :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"

#百度地图SDK
pod 'BaiduMapKit'


pod 'HYBHelperKit'

pod 'ReactiveCocoa', '~> 2.5'

end